name: Delete EPG from epgs.json

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL del EPG a eliminar'
        required: true
        default: ''

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Delete EPG from epgs.json
      run: |
        echo "Deleting EPG from epgs.json"
        epgs=$(cat epgs.json)
        updated_epgs=$(echo $epgs | jq "del(.[] | select(.url == \"${{ github.event.inputs.url }}\"))")
        echo $updated_epgs | jq '.' > epgs.json

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add epgs.json
        git commit -m "Delete EPG: ${{ github.event.inputs.url }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
